//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhThanhCong_test_webform
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong_in
    {
        public int ID { get; set; }
        public int MaHopDong { get; set; }
        public string UserID { get; set; }
        public string Time { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
