//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhThanhCong_test_webform
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong_ChiTiet
    {
        public int MaHopDong_ChiTiet { get; set; }
        public int MaHopDong { get; set; }
        public string MaVung { get; set; }
        public string SoThua { get; set; }
        public double DienTich { get; set; }
        public string ViTriDat { get; set; }
        public string LoaiDat { get; set; }
        public string TinhTrangDat { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual Vung Vung { get; set; }
    }
}
